"'name: CD Pipeline

on:
push:
branches: [main]
tags: v*

jobs:
deploy:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3

# Build and push Docker image
- name: Login to Docker Hub
uses: docker/login-action@v2
with:
username: ${{ secrets.DOCKER_HUB_USERNAME }}
password: ${{ secrets.DOCKER_HUB_TOKEN }}

- name: Build and push
uses: docker/build-push-action@v4
with:
push: true
tags: |
rag-eval:latest
rag-eval:${{ github.sha }}

# Optional: Deploy to Kubernetes/ECS
# Add deployment steps here
'"
